name = "college-attendance-monitor"
main = "src/index.tsx"
compatibility_date = "2025-09-01"
workers_dev = true

[assets]
directory = "public"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "college-attendance-monitor"
database_id = "ee13b7aa-ce14-4b1c-96cb-1d353bb1014d"
migrations_dir = "migrations"

[triggers]
crons = [
  "45 3 * * 1-6",
  "0,15,30,45 4-10 * * 1-6",
  "0,15 11 * * 1-6"
]
